version: "3.4"
networks:
  net:
    driver: overlay
    attachable: true
services:
  phpfpm:
    image: koromerzhin/php:8.4.3-apache-symfony
    # command: sh -c "composer install && apache-ctl"
    depends_on:
      - mariadb
      - mercure
      - mailhog
      - redis
    volumes:
      - ${PWD}/apps:/var/www/:rw
    networks:
      - net
    deploy:
      labels:
        - "traefik.enable=false"
