version: "3.4"
networks:
  net:
    driver: overlay
    attachable: true
services:
  phpfpm:
    image: koromerzhin/php:8.4.3-apache-symfony
    depends_on:
      - mariadb
      - mercure
      - mailhog
      - redis
    volumes:
      - ${PWD}/apps:/var/www/:rw
      - ${PWD}/conf/php.ini-development://usr/local/etc/php/conf.d/php.ini
    networks:
      - net
    deploy:
      labels:
        - "traefik.enable=false"
