framework:
    notifier:
        chatter_transports:
            bluesky: '%env(BLUESKY_DSN)%'
            discord: '%env(DISCORD_DSN)%'
            mastodon: '%env(MASTODON_DSN)%'
            telegram: '%env(TELEGRAM_DSN)%'
        texter_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email']
            high: ['email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
