vich_uploader:
  db_driver: orm
  storage: flysystem
  mappings:
    avatar:
      uri_prefix: /uploads/avatar
      upload_destination: avatar.storage
      namer:
        service: Vich\UploaderBundle\Naming\PropertyNamer
        options:
          property: username
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    chapter:
      uri_prefix: /uploads/chapter
      upload_destination: chapter.storage
      namer:
        service: Vich\UploaderBundle\Naming\PropertyNamer
        options:
          property: slug
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    edito:
      uri_prefix: /uploads/edito
      upload_destination: edito.storage
      namer:
        service: Vich\UploaderBundle\Naming\PropertyNamer
        options:
          property: title
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    history:
      uri_prefix: /uploads/history
      upload_destination: history.storage
      namer:
        service: Vich\UploaderBundle\Naming\PropertyNamer
        options:
          property: title
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    memo:
      uri_prefix: /uploads/memo
      upload_destination: memo.storage
      namer:
        service: Vich\UploaderBundle\Naming\PropertyNamer
        options:
          property: title
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    page:
      uri_prefix: /uploads/page
      upload_destination: page.storage
      namer:
        service: Vich\UploaderBundle\Naming\PropertyNamer
        options:
          property: title
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    paragraph:
      uri_prefix: /uploads/paragraph
      upload_destination: paragraph.storage
      namer:
        service: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    post:
      uri_prefix: /uploads/post
      upload_destination: post.storage
      namer:
        service: Vich\UploaderBundle\Naming\PropertyNamer
        options:
          property: title
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
