framework:
  workflows:
    chapter:
      type: 'workflow'
      audit_trail:
        enabled: true
      marking_store:
        type: 'method'
        property: 'state'
      supports:
      - Labstag\Entity\Chapter
      initial_marking: start
      places:
      - start
      - draft
      - rereading
      - published
      - rejected
      transitions:
        reread:
          from: draft
          to: rereading
        correct:
          from: rereading
          to: draft
        publish:
          from: rereading
          to: published
        reject:
          from: rereading
          to: rejected
    edito:
      type: 'workflow'
      audit_trail:
        enabled: "%kernel.debug%"
      marking_store:
        type: 'method'
        property: 'state'
      supports:
      - Labstag\Entity\Edito
      initial_marking: start
      places:
      - start
      - draft
      - rereading
      - published
      - rejected
      transitions:
        reread:
          from: draft
          to: rereading
        fix:
          from: rereading
          to: draft
        publish:
          from: rereading
          to: published
        reject:
          from: rereading
          to: rejected
    history:
      type: 'workflow'
      audit_trail:
        enabled: "%kernel.debug%"
      marking_store:
        type: 'method'
        property: 'state'
      supports:
      - Labstag\Entity\History
      initial_marking: start
      places:
      - start
      - draft
      - rereading
      - published
      - rejected
      transitions:
        reread:
          from: draft
          to: rereading
        fix:
          from: rereading
          to: draft
        publish:
          from: rereading
          to: published
        reject:
          from: rereading
          to: rejected
    memo:
      type: 'workflow'
      audit_trail:
        enabled: "%kernel.debug%"
      marking_store:
        type: 'method'
        property: 'state'
      supports:
      - Labstag\Entity\Memo
      initial_marking: start
      places:
      - start
      - draft
      - rereading
      - published
      - rejected
      transitions:
        reread:
          from: draft
          to: rereading
        fix:
          from: rereading
          to: draft
        publish:
          from: rereading
          to: published
        reject:
          from: rereading
          to: rejected
    post:
      type: 'workflow'
      audit_trail:
        enabled: "%kernel.debug%"
      marking_store:
        type: 'method'
        property: 'state'
      supports:
      - Labstag\Entity\Post
      initial_marking: start
      places:
      - start
      - draft
      - rereading
      - published
      - rejected
      transitions:
        reread:
          from: draft
          to: rereading
        fix:
          from: rereading
          to: draft
        publish:
          from: rereading
          to: published
        reject:
          from: rereading
          to: rejected
    user:
      type: 'workflow'
      audit_trail:
        enabled: "%kernel.debug%"
      marking_store:
        type: 'method'
        property: 'state'
      supports:
      - Labstag\Entity\User
      initial_marking: start
      places:
      - start
      - unverifed
      - valid
      - lostpassword
      - disable
      transitions:
        submit:
          from: start
          to: unverifed
        approval:
          from: unverifed
          to: valid
        passwordlost:
          from: valid
          to: lostpassword
        changepassword:
          from: lostpassword
          to: valid
        deactivate:
          from: valid
          to: disable
        activate:
          from: disable
          to: valid
